# Generated by Django 4.1.4 on 2023-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_mymodel_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='picture',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
